import js from "@eslint/js";

export default [
  {
    ignores: [
      "node_modules/**",
      "bus/node_modules/**",
      "shared-mcp/node_modules/**",
      "ops/node_modules/**",
      "cli/node_modules/**",
      "~/.ai-memory/**",
      "**/*.min.js",
      "dist/**",
      "build/**",
      "generated/**",
      "inbox/**",
      "imported/**",
      "structured/**",
      "cache/**",
      "coverage/**",
    ],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        setImmediate: "readonly",
        globalThis: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        TextEncoder: "readonly",
        TextDecoder: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        fetch: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        global: "readonly",
      },
    },
    rules: {
      "no-console": ["error", { allow: ["error", "warn"] }],
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-var": "error",
      "prefer-const": "warn",
    },
  },
  {
    files: [
      "cli/**/*.js",
      "bus/generate-embeddings.js",
      "ops/stress/**/*.js",
      "ops/verify/**/*.js",
      "ops/check/**/*.js",
      "ops/build/**/*.js",
      "ops/bench/**/*.js",
      "ops/adapters/**/*.js",
      "ops/migrations/**/*.js",
      "ops/setup/**/*.js",
      "ops/entity/**/*.js",
      "ops/daemon/**/*.js",
      "ops/memory/memory-archival.js",
      "ops/memory/memory-promotion-resolver.js",
      "ops/memory/memory-promotion-scorer.js",
      "ops/knowledge/knowledge-graph/cli.js",
      "retrieval/eval/**/*.js",
      "shared-mcp/proto/**/*.mjs",
    ],
    rules: {
      "no-console": "off",
    },
  },
  {
    files: [
      "ops/export/export-md.js",
      "shared-mcp/embedding-worker-script.cjs",
    ],
    rules: {
      "no-useless-escape": "off",
    },
  },
];
