import path from "node:path";
import fs from "node:fs";
import { spawn } from "node:child_process";

// ---------------------------------------------------------------------------
// Derived constants
// ---------------------------------------------------------------------------

const USER_HOME = process.env.HOME || "";
const XDG_CONFIG_HOME = process.env.XDG_CONFIG_HOME || path.join(USER_HOME, ".config");
const XDG_DATA_HOME = process.env.XDG_DATA_HOME || path.join(USER_HOME, ".local", "share");
const APP_SUPPORT = path.join(USER_HOME, "Library", "Application Support");

// ---------------------------------------------------------------------------
// Utility: isDirectory
// ---------------------------------------------------------------------------

function isDirectory(candidate) {
  if (!candidate) return false;
  try {
    return fs.statSync(candidate).isDirectory();
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Default store candidates (non-Obsidian)
// ---------------------------------------------------------------------------

function getDefaultStoreCandidates() {
  return [];
}

// ---------------------------------------------------------------------------
// resolveVaultRoot — DEPRECATED: alias for resolveStoreRoot
// ---------------------------------------------------------------------------

/**
 * @deprecated Use resolveStoreRoot() instead. resolveVaultRoot is kept for
 * backward compatibility only and will be removed in a future version.
 */
function resolveVaultRoot(options = {}) {
  return resolveStoreRoot(options);
}

// ---------------------------------------------------------------------------
// Store root resolution
// ---------------------------------------------------------------------------

const DEFAULT_STORE_ROOT = path.join(USER_HOME, ".ai-memory");
let cachedStoreRoot = null;

function resolveStoreRoot(options = {}) {
  if (cachedStoreRoot && !options.refresh) return cachedStoreRoot;

  for (const envKey of ["AI_MEMORY_STORE", "AI_MEMORY_STORE_ROOT"]) {
    const candidate = (process.env[envKey] || "").trim();
    if (candidate) {
      cachedStoreRoot = path.resolve(candidate);
      return cachedStoreRoot;
    }
  }

  const aiMemoryRoot = process.env.AI_MEMORY_ROOT || "";
  const fallback = aiMemoryRoot
    ? path.join(aiMemoryRoot, ".ai-memory")
    : DEFAULT_STORE_ROOT;

  cachedStoreRoot = fallback;
  return fallback;
}

function getInboxRoot(storeRoot) {
  return path.join(storeRoot || resolveStoreRoot(), "inbox");
}

function getGeneratedRoot(storeRoot) {
  return path.join(storeRoot || resolveStoreRoot(), "generated");
}

function getKgRoot(storeRoot) {
  return path.join(storeRoot || resolveStoreRoot(), "kg");
}

// ---------------------------------------------------------------------------
// spawnPython — macOS always uses python3
// ---------------------------------------------------------------------------

function spawnPython(args, options = {}) {
  return spawn("python3", args, {
    ...options,
    env: {
      ...(options.env || process.env),
      PYTHONUTF8: "1",
      PYTHONIOENCODING: "utf-8",
    },
  });
}

// ---------------------------------------------------------------------------
// makeWatchdogScript — bash version for macOS
// ---------------------------------------------------------------------------

function makeWatchdogScript(pidPath, callbackScript) {
  const safePidPath = String(pidPath || "/tmp/watchdog.pid").replace(/'/g, "'\\''");
  const safeCallback = String(callbackScript || "echo 'watchdog recovered'").replace(/'/g, "'\\''");
  const intervalSec = 15;

  return `\
#!/bin/bash
# AI Memory Watchdog Supervisor (bash)
# Generated by obsidian-shared-memory-bus bus/platform/darwin.js

PID_PATH='${safePidPath}'
CALLBACK='${safeCallback}'
INTERVAL=${intervalSec}

# Write our own PID so we can be identified
echo "$$" > "$PID_PATH"

is_running() {
    local pid="$1"
    if [ -z "$pid" ]; then
        return 1
    fi
    kill -0 "$pid" 2>/dev/null
}

while true; do
    sleep "$INTERVAL"

    # Read target PID (first non-empty line)
    TARGET_PID=""
    if [ -f "$PID_PATH" ]; then
        TARGET_PID=$(sed -n '1p' "$PID_PATH" | tr -d '[:space:]')
    fi

    if [ -n "$TARGET_PID" ]; then
        if ! is_running "$TARGET_PID"; then
            # Target died — invoke callback
            eval "$CALLBACK" &
            exit 0
        fi
    fi
done
`;
}

// ---------------------------------------------------------------------------
// Adapter factory
// ---------------------------------------------------------------------------

let _adapter = null;

function getDarwinAdapter() {
  if (_adapter) return _adapter;

  _adapter = {
    name: "darwin",
    storeRootDefault: DEFAULT_STORE_ROOT,
    homeEnvVar: "HOME",
    pathSep: "/",
    executables: {
      python: "python3",
      node: "node",
      powershell: null,   // No native PowerShell on macOS
    },
    watchdog: {
      scriptExtension: ".sh",
      scriptPath: path.join(USER_HOME, ".ai-memory", "watchdog-darwin.sh"),
    },
    makeWatchdogScript,
    spawnPython,
    resolveVaultRoot,
    resolveStoreRoot,
    getDefaultStoreCandidates,
    getInboxRoot,
    getGeneratedRoot,
    getKgRoot,
    // Utilities
    isDirectory,
  };

  return _adapter;
}

export { getDarwinAdapter };
