@{
    FlatRuntimeFiles = @{
        bus = @(
            "embedding-provider-registry.js"
            "generate-embeddings.js"
            "lsh-hash.js"
            "memory-bus.ps1"
            "memory-bus-agents.ps1"
            "memory-bus-helpers.ps1"
            "memory-bus-sync.ps1"
            "memory-watchdog.ps1"
            "memory-watchdog-supervisor.ps1"
            "python-runtime.js"
            "register-agent.ps1"
            "runtime-platform.ps1"
            "runtime-config.js"
            "vault-root.js"
        )
        ops = @(
            "build-handoff-pack.js"
            "build-memory-layers.js"
            "check-memory-integrity.js"
            "cleanup-inbox.ps1"
            "generate-memory-hygiene-report.js"
            "install-client-integrations.ps1"
            "memory-contract.js"
            "obsidian-blackboard-daemon.js"
            "redaction.py"
            "refresh-generated-artifacts.js"
            "run-memory-dream.ps1"
            "run-minimax-mcp.ps1"
            "run-obsidian-mcp.ps1"
            "run-pressure-test.ps1"
            "setup-wizard.ps1"
            "sync-claudemem-to-obsidian.ps1"
            "sync-openclaw-to-obsidian.js"
            "sync-shared-skills.ps1"
            "verify-client-integrations.ps1"
            "verify-integrations.ps1"
        )
        retrieval = @(
            "benchmark-architecture.py"
            "benchmark-backends.py"
            "embedding_providers.py"
            "eval-routing.py"
            "lsh_utils.py"
            "probe-models.py"
            "runtime_support.py"
            "schema_validation.py"
            "semantic-search-cli.js"
            "semantic-search-cli.test.js"
            "semantic-search.js"
            "semantic-search.py"
        )
    }
    SharedMcpFiles = @(
        "manifest.json"
        "memory-bridge.js"
        "memory-embeddings.js"
        "memory-generation.js"
        "memory-retrieval.js"
        "memory-status.js"
        "memory-tools.js"
        "omni-memory-server.js"
        "package-lock.json"
        "package.json"
        "playwright-stdio-proxy.js"
        "singleton-stdio-mcp-proxy.mjs"
        "start-default-shared-mcp.ps1"
        "start-default-shared-mcp.sh"
        "start-shared-mcp.ps1"
        "start-shared-mcp.sh"
        "status-shared-mcp.ps1"
        "status-shared-mcp.sh"
        "stop-shared-mcp.ps1"
        "stop-shared-mcp.sh"
        "write-config-snippets.ps1"
    )
    TemplateFiles = @(
        "agents.json"
        "config/runtime.json"
    )
    LegacyCleanupFiles = @(
        "benchmark-embedding-backends.py"
        "export-bundle.ps1"
        "probe-embedding-models.py"
        "run-shared-stack-pressure-test.ps1"
    )
    CliFiles = @(
        "cli/ai-memory.js"
        "cli/package.json"
    )
}
